import type { DeliveryId } from "./dropRun";
import { deliveryTarget } from "./dropRun";
import type { ApparelItem, Mission, MissionStep, NpcDef, SideMission, TrophyDef, WorldPoi } from "./types";
import { halloweenOn } from "./season";

/** Warm Memphis dusk — brand green/gold are accents only. */
export const PAL = {
  asphalt: "#22201e",
  asphaltAlt: "#262320",
  lot: "#2a2623",
  lane: "rgba(184,166,120,0.22)",
  sidewalk: "#35302a",
  sidewalkAlt: "#3b352e",
  curb: "#4a4239",
  wall: "#2b2724",
  wallAlt: "#322c28",
  wallCool: "#26282c",
  roof: "#3d3630",
  roofEdge: "#6b5c4a",
  windowDark: "#1a1715",
  windowLit: "#f2c66a",
  grass: "#4a5c3a",
  grassTip: "#6d8250",
  shadow: "rgba(74,95,107,0.28)",
  shade: "#4a5f6b",
  label: "#c4b8a8",
  ink: "#0d0b0a",
  skyTop: "#3a2e24",
  skyBot: "#1a1612",
  river0: "#2a3840",
  river1: "#1a242c",
  accent: "#1db954",
  gold: "#d4af37",
} as const;

/** Bump to force the live preview to remount the world bake. */
export const ART_REV = 93;

export const BRAND = {
  name: "$ackReligious",
  line: "KLOTHING",
  city: "Memphis",
  zip: "901",
  currency: "$ackdollars",
} as const;

export const TILE = 48;
export const WORLD_W = 64;
export const WORLD_H = 48;
export const WORLD_PX_W = WORLD_W * TILE;
export const WORLD_PX_H = WORLD_H * TILE;

export const PLAYER_SPEED = 168;
export const PLAYER_RUN = 268;

export const DEFAULT_SETTINGS = {
  master: 0.85,
  music: 0.42,
  sfx: 0.7,
  shake: true,
  rumble: true,
  cameraView: "third" as const,
  sensitivity: 1,
  quality: "high" as const,
  reduceMotion: false,
};

export const APPAREL: ApparelItem[] = [
  {
    id: "starter_tee",
    name: "Starter Green Tee",
    price: 0,
    category: "top",
    color: "#1db954",
    description: "What Benji woke up in. In the sack we trust.",
    productId: "sr-starter-tee",
  },
  {
    id: "classic_green",
    name: "Classic $ack Tee",
    price: 40,
    category: "top",
    color: "#16a34a",
    description: "The drop that put the city on notice.",
    productId: "sr-black-gold-tee",
  },
  {
    id: "moneybag_hoodie",
    name: "Moneybag Hoodie",
    price: 90,
    category: "top",
    color: "#15803d",
    description: "Heavyweight fleece. Moneybag logo front and center.",
    productId: "sr-moneybag-hoodie",
  },
  {
    id: "black_hoodie",
    name: "Midnight Hoodie",
    price: 85,
    category: "top",
    color: "#171717",
    description: "Black on black. Silent flex.",
    productId: "sr-midnight-hoodie",
  },
  {
    id: "fresh_jersey",
    name: "FRESH 38127 Jersey",
    price: 120,
    category: "top",
    color: "#0f766e",
    description: "Memphis zip. K Blanco co-sign energy.",
    productId: "sr-fresh-jersey",
  },
  {
    id: "white_cap",
    name: "White Snapback",
    price: 35,
    category: "hat",
    color: "#f5f5f5",
    description: "SackReligious script. Keep it tilted.",
    productId: "sr-white-snapback",
  },
  {
    id: "gold_chain",
    name: "Moneybag Chain",
    price: 150,
    category: "chain",
    color: "#d4af37",
    description: "Gold rope + pendant. Respect required.",
    productId: "sr-moneybag-chain",
    respectRequired: 20,
  },
  {
    id: "green_sweats",
    name: "Green Sweat Set",
    price: 110,
    category: "set",
    color: "#22c55e",
    description: "Full fit. Court to culture spot ready.",
    productId: "sr-green-sweats",
  },
  {
    id: "gold_drop",
    name: "IRL Gold Drop",
    price: 0,
    category: "set",
    color: "#c9a84c",
    description: "Verified purchase colorway. Same piece as the real order.",
    productId: "sr-gold-drop",
    irlOnly: true,
  },
  {
    id: "night_run",
    name: "Night Run Set",
    price: 140,
    category: "set",
    color: "#39ff14",
    description: "After-hours fit. Respect 30 and Drop Live.",
    productId: "sr-night-run",
    respectRequired: 30,
    dropLiveRequired: true,
  },
  {
    id: "kollab_jersey",
    name: "SR x Veli Kollab Jersey",
    price: 125,
    category: "top",
    color: "#d4af37",
    description: "This cycle's Deluxe perk. $ackReligious x Veli's Wings. IRL they keep 100% of jersey profit for 30 days.",
    productId: "sr-veli-kollab-jersey",
  },
  {
    id: "tour_black",
    name: "Worldwide Tour Tee — Black",
    price: 55,
    category: "top",
    color: "#111111",
    description: "Diamond $ · EST. 2020. Memphis on the back. Sacks Giving drop.",
    productId: "sr-tour-black",
  },
  {
    id: "tour_white",
    name: "Worldwide Tour Tee — White",
    price: 55,
    category: "top",
    color: "#f5f5f5",
    description: "White diamond $ tour tee. Rock it to the Sackrow games.",
    productId: "sr-tour-white",
  },
  {
    id: "tour_red",
    name: "Worldwide Tour Tee — Red",
    price: 55,
    category: "top",
    color: "#c41e3a",
    description: "Red tour tee. Klothing Kompany worldwide.",
    productId: "sr-tour-red",
  },
  {
    id: "jersey_white_224",
    name: "SR 224 Jersey — White",
    price: 70,
    category: "top",
    color: "#f4f4f4",
    description: "White $ackReligious 224. Court fit.",
  },
  {
    id: "jersey_blue_fresh",
    name: "SR Fresh Jersey — Blue",
    price: 70,
    category: "top",
    color: "#2563eb",
    description: "Blue Fresh jersey. Basketball action pack pending.",
  },
  {
    id: "jersey_black_fresh",
    name: "SR Fresh Jersey — Black",
    price: 70,
    category: "top",
    color: "#111111",
    description: "Black Fresh jersey. Empty-hand hoops plates.",
  },
  {
    id: "black_sackrow_11",
    name: "Sackrow Ballers #11",
    price: 0,
    category: "top",
    color: "#111111",
    description: "Black Sackrow jersey, gold #11. 901 Day court kit.",
  },
  {
    id: "blue_901_day",
    name: "901 Day Jersey",
    price: 0,
    category: "top",
    color: "#1d4ed8",
    description: "Blue 901 Day jersey. Memphis on the back.",
  },
  {
    id: "hw_doll",
    name: "Horror Doll Overalls",
    price: 0,
    category: "set",
    color: "#1d4ed8",
    description: "Halloween 2026. Striped sleeves, bloody overalls, same Benji.",
  },
  {
    id: "hw_sackrow",
    name: "Nightmare on Sackrow",
    price: 0,
    category: "top",
    color: "#111111",
    description: "Halloween 2026. Graphic tee, Sackrow on the back.",
  },
  {
    id: "hw_claw",
    name: "Claw Sweater",
    price: 0,
    category: "set",
    color: "#b91c1c",
    description: "Halloween 2026. Distressed stripes and the metal claw glove.",
  },
];

export const POIS: WorldPoi[] = [
  {
    id: "apartment",
    name: "Benji's Apartment",
    x: 5 * TILE,
    y: 7 * TILE,
    w: 4 * TILE,
    h: 4 * TILE,
    color: "#3f3f46",
    label: "HOME",
    district: "West Side",
  },
  {
    id: "store",
    name: "SackReligious HQ",
    x: 28 * TILE,
    y: 8 * TILE,
    w: 6 * TILE,
    h: 5 * TILE,
    color: "#2b2724",
    label: "HQ",
    district: "Midtown",
  },
  {
    id: "court",
    name: "901 Court",
    x: 11 * TILE,
    y: 29 * TILE,
    w: 8 * TILE,
    h: 7 * TILE,
    color: "#7c2d12",
    label: "BALL",
    district: "South Memphis",
  },
  {
    id: "neighborhood",
    name: "The Neighborhood",
    x: 46 * TILE,
    y: 10 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#1e3a5f",
    label: "HOOD",
    district: "East Memphis",
  },
  {
    id: "downtown",
    name: "Downtown Memphis",
    x: 48 * TILE,
    y: 30 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#1f2937",
    label: "DT",
    district: "Downtown",
  },
  {
    id: "culture",
    name: "The Culture Spot",
    x: 24 * TILE,
    y: 36 * TILE,
    w: 5 * TILE,
    h: 4 * TILE,
    color: "#322c28",
    label: "CULTURE",
    district: "South Main",
  },
  {
    id: "dropvan",
    name: "Drop Van",
    x: 30.4 * TILE,
    y: 19.45 * TILE,
    w: 3.2 * TILE,
    h: 1.45 * TILE,
    color: "#292524",
    label: "VAN",
    district: "Union Ave",
  },
  {
    id: "beale",
    name: "Beale Street",
    x: 18 * TILE,
    y: 19 * TILE,
    w: 8 * TILE,
    h: 3 * TILE,
    color: "#3d3630",
    label: "BEALE",
    district: "Beale",
  },
  {
    id: "pyramid",
    name: "The Pyramid",
    x: 54 * TILE,
    y: 4 * TILE,
    w: 6 * TILE,
    h: 6 * TILE,
    color: "#1c1917",
    label: "PYRAMID",
    district: "Harbor",
  },
  {
    id: "river",
    name: "Mississippi River",
    x: 0,
    y: 41 * TILE,
    w: WORLD_W * TILE,
    h: (WORLD_H - 41) * TILE,
    color: "#1e3a5f",
    label: "RIVER",
    district: "Riverfront",
  },
  {
    id: "foodtruck",
    name: "901 Catch Kitchen",
    x: 15.4 * TILE,
    y: 22.4 * TILE,
    w: 2.6 * TILE,
    h: 1.7 * TILE,
    color: "#166534",
    label: "CATCH",
    district: "Beale",
  },
  {
    id: "velis",
    name: "Veli's Wings",
    x: 43.1 * TILE,
    y: 22.5 * TILE,
    w: 2.7 * TILE,
    h: 1.7 * TILE,
    color: "#b45309",
    label: "VELI'S",
    district: "Beale",
  },
  {
    id: "brothers",
    name: "Brothers Wingz N Things",
    x: 7.6 * TILE,
    y: 22.5 * TILE,
    w: 2.7 * TILE,
    h: 1.7 * TILE,
    color: "#9f1239",
    label: "WINGZ",
    district: "Beale",
  },
  {
    id: "alley",
    name: "Gold Alley",
    x: 35.2 * TILE,
    y: 7.6 * TILE,
    w: 2.2 * TILE,
    h: 3.2 * TILE,
    color: "#c9a84c",
    label: "ALLEY",
    district: "Midtown",
  },
  {
    id: "strip",
    name: "901 Strip",
    x: 32.4 * TILE,
    y: 18.8 * TILE,
    w: 3.6 * TILE,
    h: 2.4 * TILE,
    color: "#c9a84c",
    label: "RACE",
    district: "Beale",
  },
  {
    id: "welcome",
    name: "Welkome Plaza",
    x: 24.1 * TILE,
    y: 13.5 * TILE,
    w: 3.5 * TILE,
    h: 2.5 * TILE,
    color: "#1db954",
    label: "WELKOME",
    district: "Midtown",
  },
  {
    id: "listenpost",
    name: "Artist Listening Post",
    x: 38.5 * TILE,
    y: 22.55 * TILE,
    w: 2.2 * TILE,
    h: 1.55 * TILE,
    color: "#d4af37",
    label: "POST",
    district: "Beale",
  },
  {
    id: "billboard",
    name: "901 Billboard",
    x: 46.6 * TILE,
    y: 16.2 * TILE,
    w: 2.6 * TILE,
    h: 1.5 * TILE,
    color: "#c9a84c",
    label: "BOARD",
    district: "East Memphis",
  },
  {
    id: "lanes",
    name: "901 Lanes",
    x: 20.2 * TILE,
    y: 28.4 * TILE,
    w: 6.2 * TILE,
    h: 5.2 * TILE,
    color: "#6d28d9",
    label: "LANES",
    district: "South Memphis",
  },
  {
    id: "rcmworx",
    name: "RCM WORX",
    x: 18.15 * TILE,
    y: 6.95 * TILE,
    w: 5.7 * TILE,
    h: 4.7 * TILE,
    color: "#0a0a0c",
    label: "RCM",
    district: "Midtown",
  },
  ...(halloweenOn()
    ? [
        {
          id: "haunt" as const,
          name: "Haunted House",
          x: 52 * TILE,
          y: 11.6 * TILE,
          w: 4.2 * TILE,
          h: 3.4 * TILE,
          color: "#7c2d12",
          label: "HAUNT",
          district: "East Memphis",
        },
      ]
    : []),
];

export const STREETS: { name: string; axis: "x" | "y"; tile: number }[] = [
  { name: "BEALE ST", axis: "y", tile: 20 },
  { name: "UNION AVE", axis: "y", tile: 6 },
  { name: "POPLAR AVE", axis: "y", tile: 34 },
  { name: "3RD ST", axis: "x", tile: 16 },
  { name: "FRONT ST", axis: "x", tile: 34 },
  { name: "HIGHLAND", axis: "x", tile: 50 },
];

export function createDropDayMission(opts?: { order?: DeliveryId[]; courtTarget?: number }): Mission {
  const order = opts?.order ?? ["hood", "dt", "culture"];
  const courtTarget = opts?.courtTarget ?? 8;
  const delivers: Record<DeliveryId, MissionStep> = {
    hood: {
      id: "hood",
      label: "Take the drop — Neighborhood",
      description: "Deliver the pack. Meet a supporter who actually lives this city.",
      target: deliveryTarget("hood"),
      kind: "deliver",
      reward: 50,
      done: false,
    },
    dt: {
      id: "dt",
      label: "Get fresh — Downtown",
      description: "Move product downtown, then represent. Fit is part of the work.",
      target: deliveryTarget("dt"),
      kind: "deliver",
      reward: 50,
      done: false,
    },
    culture: {
      id: "culture",
      label: "Build Respect — Culture Spot",
      description: "Show up for the culture. Respect is reputation, not a second wallet.",
      target: deliveryTarget("culture"),
      kind: "deliver",
      reward: 60,
      done: false,
    },
  };
  return {
    id: "drop_day",
    title: "The Drop Day",
    chapter: "CHAPTER 01",
    activeStep: 0,
    complete: false,
    steps: [
      {
        id: "wake",
        label: "Leave Home",
        description: "You're already inside. Walk south through the doorway onto the street.",
        target: "apartment",
        kind: "goto",
        reward: 10,
        done: false,
      },
      {
        id: "link_k",
        label: "Link Up",
        description: "Walk to SackReligious HQ and talk to K Blanco. Tonight is Drop Day.",
        target: "store",
        kind: "talk",
        reward: 25,
        done: false,
      },
      {
        id: "pickup",
        label: "Get the Drop Ready",
        description: "Inspect the wall, then secure the drop at the branded van.",
        target: "dropvan",
        kind: "pickup",
        reward: 40,
        done: false,
      },
      ...order.map((id) => ({ ...delivers[id] })),
      {
        id: "ball",
        label: "Own the 901 Court",
        description: `Meet Court OG. Pick up, dribble, shoot. Score ${courtTarget}.`,
        target: "court",
        kind: "basketball",
        reward: 45,
        done: false,
      },
      {
        id: "return",
        label: "The Drop",
        description: "Return to HQ. The floor should feel different. Drop goes live.",
        target: "store",
        kind: "return",
        reward: 100,
        done: false,
      },
    ],
  };
}

export function createAfterHoursMission(): Mission {
  return {
    id: "after_hours",
    title: "After Hours",
    chapter: "CHAPTER 02",
    activeStep: 0,
    complete: false,
    steps: [
      {
        id: "flash",
        label: "Cover Shot",
        description: "Talk to the photographer outside HQ. Drop Live needs a cover.",
        target: "store",
        kind: "talk",
        reward: 50,
        done: false,
      },
      {
        id: "alleywalk",
        label: "Gold Alley",
        description: "The alley behind HQ is open. Walk it.",
        target: "alley",
        kind: "goto",
        reward: 45,
        done: false,
      },
      {
        id: "nightball",
        label: "Sackrow Night Court",
        description: "Score 10 on the night court. Crowd is louder now.",
        target: "court",
        kind: "basketball",
        reward: 70,
        done: false,
      },
      {
        id: "nightvan",
        label: "Night Route",
        description: "Take the drop van after dark. Headlights on.",
        target: "dropvan",
        kind: "pickup",
        reward: 55,
        done: false,
      },
      {
        id: "afterparty",
        label: "Close with K",
        description: "Back to HQ. K Blanco shuts the night down.",
        target: "store",
        kind: "return",
        reward: 90,
        done: false,
      },
    ],
  };
}

export function createSideMissions(): SideMission[] {
  return [
    {
      id: "pickup_kings",
      title: "Pickup Kings",
      description: "Score 16 in a single run at 901 Court.",
      reward: 80,
      done: false,
      kind: "score",
      target: "court",
      need: 16,
    },
    {
      id: "downtown_threes",
      title: "From Downtown",
      description: "Hit 6 threes in the 3-Point Challenge at 901 Court.",
      reward: 90,
      done: false,
      kind: "score",
      target: "court",
      need: 6,
    },
    {
      id: "horse_beat",
      title: "HORSE",
      description: "Clear Court OG's HORSE calls without spelling the word.",
      reward: 100,
      done: false,
      kind: "score",
      target: "court",
      need: 5,
    },
    {
      id: "full_fit",
      title: "Full Fit",
      description: "Own four pieces from the HQ wall.",
      reward: 60,
      done: false,
      kind: "own",
      need: 4,
    },
    {
      id: "city_tour",
      title: "City Tour",
      description: "Talk to every local on the map.",
      reward: 70,
      done: false,
      kind: "talk",
      need: 6,
    },
    {
      id: "catch_grill",
      title: "Catch Kitchen",
      description: "Grill a Mississippi fish at the 901 truck.",
      reward: 40,
      done: false,
      kind: "score",
      target: "foodtruck",
      need: 1,
    },
    {
      id: "velis_plate",
      title: "Veli's Gold",
      description: "Order a plate from Veli's Wings.",
      reward: 30,
      done: false,
      kind: "score",
      target: "velis",
      need: 1,
    },
    {
      id: "brothers_crown",
      title: "Wingz N Things",
      description: "Eat with the Brothers on Beale.",
      reward: 30,
      done: false,
      kind: "score",
      target: "brothers",
      need: 1,
    },
    {
      id: "sunset_river",
      title: "Sunset at the River",
      description: "Walk the Mississippi riverfront.",
      reward: 35,
      done: false,
      kind: "visit",
      target: "river",
    },
    {
      id: "river_catch",
      title: "901 Angler",
      description: "Cast from a pier and land a fish.",
      reward: 50,
      done: false,
      kind: "score",
      target: "river",
      need: 1,
    },
    {
      id: "pyramid_pic",
      title: "Pyramid Flex",
      description: "Stand at the Pyramid and take it in.",
      reward: 40,
      done: false,
      kind: "visit",
      target: "pyramid",
    },
    {
      id: "beale_night",
      title: "Beale After Dark",
      description: "Hit Beale Street once the lights come on.",
      reward: 45,
      done: false,
      kind: "visit",
      target: "beale",
    },
    {
      id: "photo_op",
      title: "Cover Shot",
      description: "After Drop Live, talk to the photographer outside HQ.",
      reward: 70,
      done: false,
      kind: "talk",
      need: 1,
    },
    {
      id: "gold_alley",
      title: "Gold Alley",
      description: "Unlock the alley behind HQ at 25 Respect, then walk it.",
      reward: 55,
      done: false,
      kind: "visit",
      target: "alley",
    },
    {
      id: "night_van",
      title: "Night Route",
      description: "Take the drop van out after 20:00.",
      reward: 65,
      done: false,
      kind: "visit",
      target: "dropvan",
    },
    {
      id: "strip_kings",
      title: "Strip Kings",
      description: "Beat Cam in a 3-lap 901 street race.",
      reward: 120,
      done: false,
      kind: "score",
      target: "strip",
      need: 1,
    },
    {
      id: "welkome_board",
      title: "Book the Block",
      description: "Walk Welkome Plaza and read this cycle's sponsor + artist board.",
      reward: 25,
      done: false,
      kind: "visit",
      target: "welcome",
    },
    {
      id: "turkey_night",
      title: "Turkey Night",
      description: "String three strikes at 901 Lanes.",
      reward: 90,
      done: false,
      kind: "score",
      target: "lanes",
      need: 3,
    },
    {
      id: "vip_runs",
      title: "Always Ready",
      description: "Book 3 RCM WORX VIP drops. Sprinter or Escalade. On time, every time.",
      reward: 110,
      done: false,
      kind: "score",
      target: "rcmworx",
      need: 3,
    },
  ];
}

export const TROPHIES: TrophyDef[] = [
  { id: "first_steps", name: "First Steps", description: "Leave the apartment on Drop Day.", rank: "bronze" },
  { id: "family", name: "Welcome to the Family", description: "Link with K Blanco at HQ.", rank: "bronze" },
  { id: "baller", name: "Baller", description: "Score 8 at the 901 Court.", rank: "silver" },
  { id: "drop_day", name: "Drop Day", description: "Finish the main mission.", rank: "gold" },
  { id: "fresh_fit", name: "Fresh Fit", description: "Buy your first apparel drop.", rank: "bronze" },
  { id: "deep_pockets", name: "Deep Pockets", description: "Hold $400 $ackdollars.", rank: "silver" },
  { id: "court_king", name: "Court King", description: "Score 20 in one basketball run.", rank: "gold" },
  { id: "city_legend", name: "901 Legend", description: "Reach 40 Respect.", rank: "gold" },
  { id: "night_owl", name: "Night Owl", description: "Be out after 20:00.", rank: "bronze" },
  { id: "full_closet", name: "Closet Heavy", description: "Own every piece on the wall.", rank: "platinum" },
  { id: "irl_family", name: "Paid in Full", description: "Verified IRL order unlocked a game reward.", rank: "gold" },
  { id: "sackrow_s", name: "Sackrow S", description: "Finish a Drop Run at S grade.", rank: "platinum" },
  { id: "drop_live", name: "Drop Live", description: "Turn the city on. Free roam begins.", rank: "gold" },
  { id: "after_hours", name: "After Hours", description: "Finish Chapter 2. The night stays loud.", rank: "platinum" },
  { id: "strip_king", name: "Strip King", description: "Beat Cam on the 901 loop.", rank: "gold" },
  { id: "river_rat", name: "River Rat", description: "Land a fish on the Mississippi.", rank: "bronze" },
  { id: "block_eats", name: "Block Eats", description: "Eat at every food truck on Beale.", rank: "silver" },
  { id: "lane_king", name: "Lane King", description: "Throw a turkey at 901 Lanes.", rank: "gold" },
  { id: "always_ready", name: "Always Ready", description: "Complete 3 RCM WORX VIP runs. On time, every time.", rank: "gold" },
  { id: "after_dark", name: "Halloween Master", description: "Clear Halloween After Dark. Letters, house, and the night runs.", rank: "platinum" },
];

export const NPCS: NpcDef[] = [
  {
    id: "k_blanco",
    name: "K Blanco",
    x: 32.5 * TILE,
    y: 13.8 * TILE,
    color: "#f5d0a9",
    dialogue: [
      "You made it. I needed somebody who moves like the city, not like a tourist.",
      "Tonight is Drop Day. We do this clean — product out, Respect in.",
      "Shop the wall if you want the fit. The real drop still has to hit the streets.",
    ],
    missionTalk: "Benji. Tonight is Drop Day. Grab the van, hit three spots, then come back to me.",
    isKBlanco: true,
  },
  {
    id: "supporter_1",
    name: "Local Supporter",
    x: 48 * TILE,
    y: 12 * TILE,
    color: "#a3a3a3",
    dialogue: [
      "You Benji? K said the new drop was coming through this block.",
      "Don't just drop it and bounce. Talk to people. That's how Respect works.",
    ],
  },
  {
    id: "downtown_fan",
    name: "901 Fan",
    x: 50 * TILE,
    y: 32 * TILE,
    color: "#e5e5e5",
    dialogue: ["Downtown don't care about talk. They care who showed up.", "You got that energy, Benji. Wear it."],
  },
  {
    id: "culture_host",
    name: "Culture Host",
    x: 26 * TILE,
    y: 38 * TILE,
    color: "#c4b8a8",
    dialogue: ["Culture spot remembers who pulled up when it was quiet.", "You moved product. Now move with purpose."],
  },
  {
    id: "court_coach",
    name: "Court OG",
    x: 13 * TILE,
    y: 31 * TILE,
    color: "#fdba74",
    dialogue: [
      "Court's open. Pick the ball up, gather, then let it fly.",
      "Don't rush the release. Green window. Miss, rebound, go again.",
      "After Drop Day we run HORSE and the 3-point. Don't come light.",
    ],
  },
  {
    id: "street_npc",
    name: "Memphis Local",
    x: 20 * TILE,
    y: 18 * TILE,
    color: "#c4b8a8",
    dialogue: ["Man, this city rockin' with the brand heavy.", "Pyramid looks different on Drop Day."],
    wander: true,
  },
  {
    id: "beale_dj",
    name: "Beale DJ",
    x: 22 * TILE,
    y: 21 * TILE,
    color: "#fbbf24",
    dialogue: ["Beale don't sleep. Brand either.", "When the neon hits, the city talks."],
    wander: true,
  },
  {
    id: "photog",
    name: "Block Photog",
    x: 31.2 * TILE,
    y: 13.6 * TILE,
    color: "#c9a84c",
    dialogue: [
      "Hold up. Chin down, chain out. That's the cover.",
      "Drop Live looks different when the flash hits the gold.",
      "Don't duck the camera. The brand needs the face that ran the drop.",
    ],
  },
  {
    id: "cam",
    name: "Cam",
    x: 33.6 * TILE,
    y: 19.7 * TILE,
    color: "#c9a84c",
    dialogue: [
      "Strip's open. Gold coupe versus the drop van.",
      "Three laps. Beale, Highland, Poplar, 3rd, Union, Front. Don't brake for the lights — I won't.",
    ],
  },
  {
    id: "lane_clerk",
    name: "Dee",
    x: 24.9 * TILE,
    y: 32 * TILE,
    color: "#c084fc",
    dialogue: [
      "Right off 901 Court. Shoes on the house if you got the arm.",
      "Hold to charge. Lean for hook. Pocket lives on the right.",
      "Turkey pays. Don't gutter on my floor.",
    ],
  },
  {
    id: "rcm_chauffeur",
    name: "Rico",
    x: 21 * TILE,
    y: 11.15 * TILE,
    color: "#c9a84c",
    dialogue: [
      "RCM WORX. SackReligious rides first class now. On time, every time.",
      "Sprinter holds eight — captain chairs, Wi-Fi, fridge. Escalade ESV is the executive whip.",
      "Harbor FBO, Beale, the Pyramid. Book it. We don't miss.",
    ],
  },
];

export const DROP_LIVE_LINES = [
  "That's the sound. Drop's live. The block felt that.",
  "Cameras outside. People in the fit. That's because you showed up.",
  "Free roam now. Side jobs print Respect. Don't waste the night.",
];

export const AFTER_HOURS_LINES = [
  "That's the cover. Gold Alley, night court, van after dark.",
  "You didn't just drop product. You dropped a night.",
  "After Hours is closed. Side jobs still print Respect. Don't disappear.",
];

export const TIPS = [
  "Hold Shift or the right face button to sprint the block.",
  "Release the shot in the green window for a swish.",
  "Streaks at the court pay extra $ackdollars.",
  "Press Start or Esc for the map, missions, and wardrobe.",
  "A DualSense or Xbox pad works — left stick to move, South to talk.",
  "Night on Beale hits different. Stay out after 20:00.",
  "Shop the wall at HQ. Fit changes how the city sees you.",
  "Race Cam at the 901 Strip. Three laps around the city.",
  "Welkome Plaza books 2 sponsors and 2 artists every 30 days.",
  "Worldwide Tour tees are in the locker. Black, white, or red.",
  "Sacks Giving Weekend flyers are up on Beale, the court, and HQ.",
  "901 Lanes is east of 901 Court. Pink neon. Walk in and bowl.",
  "RCM WORX sits west of HQ on Union. Black Sprinter and Escalade. Book a VIP drop.",
];

export const SAVE_KEY = "sackreligious-memphis-v3";
export const SAVE_KEY_LEGACY = "sackreligious-memphis-v2";
export const SAVE_KEY_LEGACY_V1 = "sackreligious-memphis-v1";
export const SAVE_VERSION = 3 as const;
