/* Generated by scripts/analyze-character-alpha.py. Do not hand-edit. */
export type AlphaBounds = {
  pxWidth: number;
  pxHeight: number;
  visibleTop: number;
  visibleBottom: number;
  visibleLeft: number;
  visibleRight: number;
  bottomPadding: number;
};

export const characterBounds: Record<string, AlphaBounds> = {
  '/game-v2/characters/benji/back.png': { pxWidth: 197, pxHeight: 515, visibleTop: 0, visibleBottom: 514, visibleLeft: 0, visibleRight: 196, bottomPadding: 0 },
  '/game-v2/characters/benji/front.png': { pxWidth: 200, pxHeight: 535, visibleTop: 0, visibleBottom: 534, visibleLeft: 0, visibleRight: 199, bottomPadding: 0 },
  '/game-v2/characters/benji/left.png': { pxWidth: 216, pxHeight: 530, visibleTop: 0, visibleBottom: 529, visibleLeft: 0, visibleRight: 215, bottomPadding: 0 },
  '/game-v2/characters/benji/right.png': { pxWidth: 226, pxHeight: 538, visibleTop: 0, visibleBottom: 537, visibleLeft: 0, visibleRight: 225, bottomPadding: 0 },
  '/game-v2/characters/benji/walk.png': { pxWidth: 672, pxHeight: 1646, visibleTop: 0, visibleBottom: 1645, visibleLeft: 0, visibleRight: 671, bottomPadding: 0 },
  '/game-v2/characters/court-og/back.png': { pxWidth: 294, pxHeight: 612, visibleTop: 0, visibleBottom: 611, visibleLeft: 0, visibleRight: 293, bottomPadding: 0 },
  '/game-v2/characters/court-og/front.png': { pxWidth: 321, pxHeight: 612, visibleTop: 0, visibleBottom: 611, visibleLeft: 0, visibleRight: 320, bottomPadding: 0 },
  '/game-v2/characters/court-og/left.png': { pxWidth: 275, pxHeight: 612, visibleTop: 0, visibleBottom: 611, visibleLeft: 0, visibleRight: 274, bottomPadding: 0 },
  '/game-v2/characters/court-og/right.png': { pxWidth: 269, pxHeight: 640, visibleTop: 0, visibleBottom: 639, visibleLeft: 0, visibleRight: 268, bottomPadding: 0 },
  '/game-v2/characters/k-blanco/back.png': { pxWidth: 175, pxHeight: 474, visibleTop: 0, visibleBottom: 473, visibleLeft: 0, visibleRight: 174, bottomPadding: 0 },
  '/game-v2/characters/k-blanco/front.png': { pxWidth: 170, pxHeight: 512, visibleTop: 4, visibleBottom: 511, visibleLeft: 0, visibleRight: 169, bottomPadding: 0 },
  '/game-v2/characters/k-blanco/left.png': { pxWidth: 107, pxHeight: 568, visibleTop: 0, visibleBottom: 567, visibleLeft: 0, visibleRight: 106, bottomPadding: 0 },
  '/game-v2/characters/k-blanco/portrait.png': { pxWidth: 441, pxHeight: 669, visibleTop: 0, visibleBottom: 666, visibleLeft: 0, visibleRight: 440, bottomPadding: 2 },
  '/game-v2/characters/k-blanco/right.png': { pxWidth: 121, pxHeight: 568, visibleTop: 70, visibleBottom: 564, visibleLeft: 0, visibleRight: 109, bottomPadding: 3 },
  '/game-v2/characters/mama-dee/back.png': { pxWidth: 265, pxHeight: 762, visibleTop: 1, visibleBottom: 761, visibleLeft: 0, visibleRight: 264, bottomPadding: 0 },
  '/game-v2/characters/mama-dee/front.png': { pxWidth: 270, pxHeight: 760, visibleTop: 0, visibleBottom: 759, visibleLeft: 0, visibleRight: 269, bottomPadding: 0 },
  '/game-v2/characters/mama-dee/left.png': { pxWidth: 267, pxHeight: 761, visibleTop: 0, visibleBottom: 760, visibleLeft: 0, visibleRight: 266, bottomPadding: 0 },
  '/game-v2/characters/mama-dee/right.png': { pxWidth: 227, pxHeight: 760, visibleTop: 0, visibleBottom: 759, visibleLeft: 0, visibleRight: 226, bottomPadding: 0 },
  '/game-v2/characters/nitro/back.png': { pxWidth: 271, pxHeight: 745, visibleTop: 0, visibleBottom: 744, visibleLeft: 0, visibleRight: 270, bottomPadding: 0 },
  '/game-v2/characters/nitro/front.png': { pxWidth: 291, pxHeight: 748, visibleTop: 0, visibleBottom: 747, visibleLeft: 0, visibleRight: 290, bottomPadding: 0 },
  '/game-v2/characters/nitro/left.png': { pxWidth: 270, pxHeight: 752, visibleTop: 0, visibleBottom: 750, visibleLeft: 0, visibleRight: 269, bottomPadding: 1 },
  '/game-v2/characters/nitro/right.png': { pxWidth: 252, pxHeight: 750, visibleTop: 0, visibleBottom: 749, visibleLeft: 0, visibleRight: 251, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-01-walk.png': { pxWidth: 595, pxHeight: 1551, visibleTop: 0, visibleBottom: 1550, visibleLeft: 0, visibleRight: 594, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-01.png': { pxWidth: 492, pxHeight: 1599, visibleTop: 0, visibleBottom: 1598, visibleLeft: 0, visibleRight: 491, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-02-walk.png': { pxWidth: 632, pxHeight: 1573, visibleTop: 0, visibleBottom: 1572, visibleLeft: 0, visibleRight: 631, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-02.png': { pxWidth: 546, pxHeight: 1599, visibleTop: 0, visibleBottom: 1598, visibleLeft: 0, visibleRight: 545, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-03-walk.png': { pxWidth: 540, pxHeight: 1635, visibleTop: 0, visibleBottom: 1634, visibleLeft: 0, visibleRight: 539, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-03.png': { pxWidth: 516, pxHeight: 1637, visibleTop: 0, visibleBottom: 1635, visibleLeft: 0, visibleRight: 515, bottomPadding: 1 },
  '/game-v2/characters/pedestrians/female-04-walk.png': { pxWidth: 657, pxHeight: 1592, visibleTop: 0, visibleBottom: 1591, visibleLeft: 0, visibleRight: 656, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/female-04.png': { pxWidth: 592, pxHeight: 1624, visibleTop: 0, visibleBottom: 1623, visibleLeft: 0, visibleRight: 591, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/male-01-walk.png': { pxWidth: 658, pxHeight: 1557, visibleTop: 0, visibleBottom: 1556, visibleLeft: 0, visibleRight: 657, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/male-01.png': { pxWidth: 611, pxHeight: 1601, visibleTop: 0, visibleBottom: 1597, visibleLeft: 0, visibleRight: 610, bottomPadding: 3 },
  '/game-v2/characters/pedestrians/male-02-walk.png': { pxWidth: 696, pxHeight: 1607, visibleTop: 0, visibleBottom: 1605, visibleLeft: 0, visibleRight: 695, bottomPadding: 1 },
  '/game-v2/characters/pedestrians/male-02.png': { pxWidth: 635, pxHeight: 1656, visibleTop: 0, visibleBottom: 1655, visibleLeft: 0, visibleRight: 634, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/male-03-walk.png': { pxWidth: 657, pxHeight: 1589, visibleTop: 0, visibleBottom: 1585, visibleLeft: 0, visibleRight: 656, bottomPadding: 3 },
  '/game-v2/characters/pedestrians/male-03.png': { pxWidth: 639, pxHeight: 1595, visibleTop: 0, visibleBottom: 1592, visibleLeft: 0, visibleRight: 638, bottomPadding: 2 },
  '/game-v2/characters/pedestrians/male-04-walk.png': { pxWidth: 558, pxHeight: 1571, visibleTop: 0, visibleBottom: 1570, visibleLeft: 0, visibleRight: 557, bottomPadding: 0 },
  '/game-v2/characters/pedestrians/male-04.png': { pxWidth: 578, pxHeight: 1598, visibleTop: 0, visibleBottom: 1597, visibleLeft: 0, visibleRight: 577, bottomPadding: 0 },
  '/game-v2/characters/strike/back.png': { pxWidth: 283, pxHeight: 626, visibleTop: 0, visibleBottom: 625, visibleLeft: 0, visibleRight: 282, bottomPadding: 0 },
  '/game-v2/characters/strike/front.png': { pxWidth: 259, pxHeight: 668, visibleTop: 0, visibleBottom: 667, visibleLeft: 0, visibleRight: 258, bottomPadding: 0 },
  '/game-v2/characters/strike/left.png': { pxWidth: 263, pxHeight: 631, visibleTop: 0, visibleBottom: 630, visibleLeft: 0, visibleRight: 262, bottomPadding: 0 },
  '/game-v2/characters/strike/right.png': { pxWidth: 234, pxHeight: 619, visibleTop: 0, visibleBottom: 618, visibleLeft: 0, visibleRight: 233, bottomPadding: 0 },
  '/game-v2/characters/unc-j/back.png': { pxWidth: 280, pxHeight: 710, visibleTop: 0, visibleBottom: 709, visibleLeft: 0, visibleRight: 279, bottomPadding: 0 },
  '/game-v2/characters/unc-j/front.png': { pxWidth: 280, pxHeight: 631, visibleTop: 0, visibleBottom: 630, visibleLeft: 0, visibleRight: 279, bottomPadding: 0 },
  '/game-v2/characters/unc-j/left.png': { pxWidth: 306, pxHeight: 633, visibleTop: 0, visibleBottom: 632, visibleLeft: 0, visibleRight: 305, bottomPadding: 0 },
  '/game-v2/characters/unc-j/right.png': { pxWidth: 298, pxHeight: 625, visibleTop: 0, visibleBottom: 624, visibleLeft: 0, visibleRight: 297, bottomPadding: 0 },
};
