"""Measure visible alpha bounds for every game-v2 character frame.

Writes src/game-v2/assets/character-bounds.ts. Do not hand-edit that file.
"""
from __future__ import annotations

import os
from pathlib import Path

from PIL import Image

ROOT = Path("public/game-v2/characters")
OUT = Path("src/game-v2/assets/character-bounds.ts")
ALPHA = 28
MIN_SPAN = 4


def measure(path: Path) -> dict:
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    pixels = image.load()
    row_count = [0] * height
    col_count = [0] * width
    for y in range(height):
        for x in range(width):
            if pixels[x, y][3] >= ALPHA:
                row_count[y] += 1
                col_count[x] += 1
    rows = [y for y, count in enumerate(row_count) if count >= MIN_SPAN]
    cols = [x for x, count in enumerate(col_count) if count >= MIN_SPAN]
    if not rows or not cols:
        rows = [0, height - 1]
        cols = [0, width - 1]
    top, bottom = rows[0], rows[-1]
    left, right = cols[0], cols[-1]
    return {
        "pxWidth": width,
        "pxHeight": height,
        "visibleTop": top,
        "visibleBottom": bottom,
        "visibleLeft": left,
        "visibleRight": right,
        "bottomPadding": (height - 1) - bottom,
    }


def main() -> None:
    records: dict[str, dict] = {}
    for path in sorted(ROOT.rglob("*.png")):
        key = "/" + path.as_posix().removeprefix("public/")
        records[key] = measure(path)
    lines = [
        "/* Generated by scripts/analyze-character-alpha.py. Do not hand-edit. */",
        "export type AlphaBounds = {",
        "  pxWidth: number;",
        "  pxHeight: number;",
        "  visibleTop: number;",
        "  visibleBottom: number;",
        "  visibleLeft: number;",
        "  visibleRight: number;",
        "  bottomPadding: number;",
        "};",
        "",
        "export const characterBounds: Record<string, AlphaBounds> = {",
    ]
    for key, bounds in records.items():
        body = ", ".join(f"{name}: {value}" for name, value in bounds.items())
        lines.append(f"  {key!r}: {{ {body} }},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"{len(records)} frames -> {OUT}")

    vehicle_records = {}
    for path in sorted(Path("public/game-v2/vehicles").glob("*.png")):
        vehicle_records["/" + path.as_posix().removeprefix("public/")] = measure(path)
    vehicle_lines = ["/* Generated by scripts/analyze-character-alpha.py. Do not hand-edit. */",
                     'import type { AlphaBounds } from "./character-bounds";',
                     "export const vehicleBounds: Record<string, AlphaBounds> = {"]
    for key, bounds in vehicle_records.items():
        body = ", ".join(f"{name}: {value}" for name, value in bounds.items())
        vehicle_lines.append(f"  {key!r}: {{ {body} }},")
    vehicle_lines.extend(["};", ""])
    Path("src/game-v2/assets/vehicle-bounds.ts").write_text("\n".join(vehicle_lines))


if __name__ == "__main__":
    os.chdir(Path(__file__).resolve().parents[1])
    main()
