import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=swiftshader", "--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "domcontentloaded" });
await page.waitForFunction(() => window.__SACK_V2_INPUT__, { timeout: 20000 });
await page.evaluate(() => localStorage.removeItem("sack-v2"));
await page.evaluate(() => window.__SACK_V2_INPUT__.setShot({ place: "hq", x: 82.15, z: 203.55, yaw: Math.PI, dollars: 240, respect: 12, carrying: false, delivered: false, mission: "Talk to K Blanco", dialogue: "" }));
await page.waitForTimeout(250);
await page.evaluate(() => window.__SACK_V2_INPUT__.press("KeyE"));
await page.waitForTimeout(350);
await page.evaluate(() => window.__SACK_V2_INPUT__.setShot({ x: 52, z: -12.9, yaw: Math.PI }));
await page.waitForTimeout(200);
await page.evaluate(() => window.__SACK_V2_INPUT__.press("KeyE"));
await page.waitForTimeout(500);
const done = await page.evaluate(() => window.__SACK_V2__);
await page.reload({ waitUntil: "domcontentloaded" });
await page.waitForFunction(() => window.__SACK_V2__, { timeout: 20000 });
await page.waitForTimeout(400);
const again = await page.evaluate(() => ({ dollars: window.__SACK_V2__.dollars, respect: window.__SACK_V2__.respect, mission: window.__SACK_V2__.mission, carrying: window.__SACK_V2__.carrying }));
console.log(JSON.stringify({ done: { dollars: done.dollars, respect: done.respect, carrying: done.carrying, mission: done.mission }, again }));
await page.evaluate(() => window.__SACK_V2_INPUT__.setShot({ x: 24, z: -8.4, yaw: Math.PI, facing: "back", night: false, dist: 7.2, dialogue: "", mission: "Walk the block to SackReligious HQ", dollars: 240, respect: 12, carrying: false }));
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/artifacts/v2-hq-day.png", animations: "disabled", timeout: 45000 });
await page.evaluate(() => window.__SACK_V2_INPUT__.setShot({ x: 24, z: -8.4, yaw: Math.PI, facing: "back", night: true, dist: 7.2, dialogue: "" }));
await page.waitForTimeout(300);
await page.screenshot({ path: "/workspace/artifacts/v2-hq-night.png", animations: "disabled", timeout: 45000 });
await page.setViewportSize({ width: 390, height: 844 });
await page.evaluate(() => window.__SACK_V2_INPUT__.setShot({ x: -30.2, z: 5.55, yaw: Math.PI / 2, facing: "back", night: false, dialogue: "", mission: "Walk the block to SackReligious HQ", dollars: 240, respect: 12, carrying: false }));
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/artifacts/v2-mobile.png", animations: "disabled", timeout: 45000 });
console.log("retaken");
await browser.close();
